<?php

namespace Database\Seeders\Proveedores;

use App\Models\Proveedores\Rubro;
use App\Models\Proveedores\Subrubro;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RubroSubrubroSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        Rubro::create(['id' => 	1	, 'nombre' => 'Aislaciones']);
Rubro::create(['id' => 	2	, 'nombre' => 'Alquileres']);
Rubro::create(['id' => 	3	, 'nombre' => 'Andamios']);
Rubro::create(['id' => 	4	, 'nombre' => 'Auditorías']);
Rubro::create(['id' => 	5	, 'nombre' => 'Automatismos, control y PLC']);
Rubro::create(['id' => 	6	, 'nombre' => 'Automotores']);
Rubro::create(['id' => 	7	, 'nombre' => 'Balanceo equipos rotantes']);
Rubro::create(['id' => 	8	, 'nombre' => 'Baterías']);
Rubro::create(['id' => 	9	, 'nombre' => 'Bombas']);
Rubro::create(['id' => 	10	, 'nombre' => 'Buceo']);
Rubro::create(['id' => 	11	, 'nombre' => 'Calderas']);
Rubro::create(['id' => 	12	, 'nombre' => 'Calibración protecciones eléctricas']);
Rubro::create(['id' => 	13	, 'nombre' => 'Capacitaciones']);
Rubro::create(['id' => 	14	, 'nombre' => 'Carbones']);
Rubro::create(['id' => 	15	, 'nombre' => 'Catering']);
Rubro::create(['id' => 	16	, 'nombre' => 'Chimeneas']);
Rubro::create(['id' => 	17	, 'nombre' => 'Climatización Industrial']);
Rubro::create(['id' => 	18	, 'nombre' => 'Cojinetes']);
Rubro::create(['id' => 	19	, 'nombre' => 'Combustibles']);
Rubro::create(['id' => 	20	, 'nombre' => 'Compresores']);
Rubro::create(['id' => 	21	, 'nombre' => 'Conductores Eléctricos y Accesorios']);
Rubro::create(['id' => 	22	, 'nombre' => 'Consultoria']);
Rubro::create(['id' => 	23	, 'nombre' => 'Control de plagas']);
Rubro::create(['id' => 	24	, 'nombre' => 'Correo']);
Rubro::create(['id' => 	25	, 'nombre' => 'Declaración jurada de residuos']);
Rubro::create(['id' => 	26	, 'nombre' => 'Derrame control, almacenamiento']);
Rubro::create(['id' => 	27	, 'nombre' => 'Elementos de maniobra MT']);
Rubro::create(['id' => 	28	, 'nombre' => 'Elementos de protección personal']);
Rubro::create(['id' => 	29	, 'nombre' => 'Embragues y frenos industriales']);
Rubro::create(['id' => 	30	, 'nombre' => 'Empaquetaduras']);
Rubro::create(['id' => 	31	, 'nombre' => 'Ensayos']);
Rubro::create(['id' => 	32	, 'nombre' => 'Equipos de Medición']);
Rubro::create(['id' => 	33	, 'nombre' => 'Equipos eléctricos e Instalaciones eléctricas']);
Rubro::create(['id' => 	34	, 'nombre' => 'Estudios medioambientales']);
Rubro::create(['id' => 	35	, 'nombre' => 'Extintores, matafuegos y elementos antincendios']);
Rubro::create(['id' => 	36	, 'nombre' => 'Ferretería Indistrial']);
Rubro::create(['id' => 	37	, 'nombre' => 'Filtros industriales']);
Rubro::create(['id' => 	38	, 'nombre' => 'Fundidoras y Metalúrgicas']);
Rubro::create(['id' => 	39	, 'nombre' => 'Gases industriales']);
Rubro::create(['id' => 	40	, 'nombre' => 'Generadores']);
Rubro::create(['id' => 	41	, 'nombre' => 'Grupos Electrógenos']);
Rubro::create(['id' => 	42	, 'nombre' => 'Hidráulica']);
Rubro::create(['id' => 	43	, 'nombre' => 'Honorarios Profesionales']);
Rubro::create(['id' => 	44	, 'nombre' => 'Iluminación']);
Rubro::create(['id' => 	45	, 'nombre' => 'Intercambiadores de calor']);
Rubro::create(['id' => 	46	, 'nombre' => 'Laboratorios']);
Rubro::create(['id' => 	47	, 'nombre' => 'Insumos de Librería ']);
Rubro::create(['id' => 	48	, 'nombre' => 'Limpieza industrial']);
Rubro::create(['id' => 	49	, 'nombre' => 'Lubricantes, aceites y grasas']);
Rubro::create(['id' => 	50	, 'nombre' => 'Mecanizados, Corte y Construcciones Metalúrgicas']);
Rubro::create(['id' => 	51	, 'nombre' => 'Medicina Laboral - Insumos']);
Rubro::create(['id' => 	52	, 'nombre' => 'Medicina Laboral - ortopedias y otros']);
Rubro::create(['id' => 	53	, 'nombre' => 'Medicina Laboral Servicios']);
Rubro::create(['id' => 	54	, 'nombre' => 'Medios de Elevación e Izaje']);
Rubro::create(['id' => 	55	, 'nombre' => 'Mobiliario de Oficina']);
Rubro::create(['id' => 	56	, 'nombre' => 'Monitoreos ambientales/ seguridad e higiene']);
Rubro::create(['id' => 	57	, 'nombre' => 'Montacargas y ascensores']);
Rubro::create(['id' => 	58	, 'nombre' => 'Montajes Eléctricos']);
Rubro::create(['id' => 	59	, 'nombre' => 'Montajes Industriales']);
Rubro::create(['id' => 	60	, 'nombre' => 'Motores Eléctricos']);
Rubro::create(['id' => 	61	, 'nombre' => 'Hospedaje y Transporte']);
Rubro::create(['id' => 	62	, 'nombre' => 'Multiplicadores / Reductores de Velocidad']);
Rubro::create(['id' => 	63	, 'nombre' => 'Obras Civiles - Intendencia']);
Rubro::create(['id' => 	64	, 'nombre' => 'Suscripciones']);
Rubro::create(['id' => 	65	, 'nombre' => 'Permisos ambientales']);
Rubro::create(['id' => 	66	, 'nombre' => 'Permisos ambientales ']);
Rubro::create(['id' => 	67	, 'nombre' => 'Planta de Osmosis Inversa']);
Rubro::create(['id' => 	68	, 'nombre' => 'Productos químicos industriales']);
Rubro::create(['id' => 	69	, 'nombre' => 'Protección anticorrosiva, catódica y conexionado']);
Rubro::create(['id' => 	70	, 'nombre' => 'Radiadores, enfriadores, condensadores, calefactores, intercoolers']);
Rubro::create(['id' => 	71	, 'nombre' => 'Residuos Industriales']);
Rubro::create(['id' => 	72	, 'nombre' => 'Retiro, transporte y disposición final de residuos']);
Rubro::create(['id' => 	73	, 'nombre' => 'Rodamientos']);
Rubro::create(['id' => 	74	, 'nombre' => 'Ropa de trabajo']);
Rubro::create(['id' => 	75	, 'nombre' => 'Seguros']);
Rubro::create(['id' => 	76	, 'nombre' => 'Señalización de seguridad']);
Rubro::create(['id' => 	77	, 'nombre' => 'Limpieza']);
Rubro::create(['id' => 	78	, 'nombre' => 'Servicios Públicos ']);
Rubro::create(['id' => 	79	, 'nombre' => 'Servicios y regalos empresariales']);
Rubro::create(['id' => 	80	, 'nombre' => 'Sistemas contra Incendio']);
Rubro::create(['id' => 	81	, 'nombre' => 'Sistemas/ Comunicaciones']);
Rubro::create(['id' => 	82	, 'nombre' => 'Tanques de Combustible']);
Rubro::create(['id' => 	83	, 'nombre' => 'Termocuplas']);
Rubro::create(['id' => 	84	, 'nombre' => 'Tornería']);
Rubro::create(['id' => 	85	, 'nombre' => 'Transformadores']);
Rubro::create(['id' => 	86	, 'nombre' => 'Transportes - Fletes']);
Rubro::create(['id' => 	87	, 'nombre' => 'Tratamientos Superficiales']);
Rubro::create(['id' => 	88	, 'nombre' => 'Tratamientos Térmicos']);
Rubro::create(['id' => 	89	, 'nombre' => 'Tubos, Caños e Insumos Metalúrgicos Pesados']);
Rubro::create(['id' => 	90	, 'nombre' => 'Turbinas de Gas']);
Rubro::create(['id' => 	91	, 'nombre' => 'Turbinas de Vapor']);
Rubro::create(['id' => 	92	, 'nombre' => 'UPS']);
Rubro::create(['id' => 	93	, 'nombre' => 'Válvulas']);
				







        Subrubro::create(['id' =>	1	, 'rubro_id' =>	1	, 'nombre' => 'Aislación térmica']);
        Subrubro::create(['id' =>	2	, 'rubro_id' =>	1	, 'nombre' => 'Fumistería y Gunitado']);
        Subrubro::create(['id' =>	3	, 'rubro_id' =>	2	, 'nombre' => 'Inmuebles']);
        Subrubro::create(['id' =>	4	, 'rubro_id' =>	2	, 'nombre' => 'Cocheras']);
        Subrubro::create(['id' =>	5	, 'rubro_id' =>	3	, 'nombre' => 'Provisión - Alquiler - Montaje - Repuestos - Accesorios']);
        Subrubro::create(['id' =>	6	, 'rubro_id' =>	4	, 'nombre' => 'Sistema Gestión Ambiental']);
        Subrubro::create(['id' =>	7	, 'rubro_id' =>	4	, 'nombre' => 'Sistema Gestión Seguridad e Higiene ']);
        Subrubro::create(['id' =>	8	, 'rubro_id' =>	4	, 'nombre' => 'Auditoría contable']);
        Subrubro::create(['id' =>	9	, 'rubro_id' =>	5	, 'nombre' => 'Diseño e Instalación']);
        Subrubro::create(['id' =>	10	, 'rubro_id' =>	5	, 'nombre' => 'Equipos']);
        Subrubro::create(['id' =>	11	, 'rubro_id' =>	5	, 'nombre' => 'Insumos']);
        Subrubro::create(['id' =>	12	, 'rubro_id' =>	5	, 'nombre' => 'Medición']);
        Subrubro::create(['id' =>	13	, 'rubro_id' =>	5	, 'nombre' => 'Válvulas y actuadores']);
        Subrubro::create(['id' =>	14	, 'rubro_id' =>	6	, 'nombre' => 'Servicios mantenimiento Automotores']);
        Subrubro::create(['id' =>	15	, 'rubro_id' =>	6	, 'nombre' => 'Repuestos Automotores']);
        Subrubro::create(['id' =>	16	, 'rubro_id' =>	6	, 'nombre' => 'Automóviles']);
        Subrubro::create(['id' =>	17	, 'rubro_id' =>	6	, 'nombre' => 'Combustibles Automotores']);
        Subrubro::create(['id' =>	18	, 'rubro_id' =>	7	, 'nombre' => 'Servicio']);
        Subrubro::create(['id' =>	19	, 'rubro_id' =>	8	, 'nombre' => 'Banco de Batería para UPS (Provisión - Repuestos - Instalación - Mantenimiento - Ensayos)']);
        Subrubro::create(['id' =>	20	, 'rubro_id' =>	8	, 'nombre' => 'Batería alcalina Níquel Cadmio (Provisión - Repuestos - Instalación - Mantenimiento - Ensayos)']);
        Subrubro::create(['id' =>	21	, 'rubro_id' =>	8	, 'nombre' => 'Batería automotor (Provisión - Repuestos)']);
        Subrubro::create(['id' =>	22	, 'rubro_id' =>	8	, 'nombre' => 'Batería Gel (Provisión - Instalación - Mantenimiento - Ensayos)']);
        Subrubro::create(['id' =>	23	, 'rubro_id' =>	8	, 'nombre' => 'Batería o Pila alcalina común o recargable (Provisión)']);
        Subrubro::create(['id' =>	24	, 'rubro_id' =>	8	, 'nombre' => 'Batería Plomo Ácido (Provisión - Repuestos - Instalación - Mantenimiento - Ensayos)']);
        Subrubro::create(['id' =>	25	, 'rubro_id' =>	9	, 'nombre' => 'Ensayos']);
        Subrubro::create(['id' =>	26	, 'rubro_id' =>	9	, 'nombre' => 'Instalación']);
        Subrubro::create(['id' =>	27	, 'rubro_id' =>	9	, 'nombre' => 'Provisión - Repuestos - Sellos']);
        Subrubro::create(['id' =>	28	, 'rubro_id' =>	9	, 'nombre' => 'Reparación - Mantenimiento']);
        Subrubro::create(['id' =>	29	, 'rubro_id' =>	10	, 'nombre' => 'Servicio']);
        Subrubro::create(['id' =>	30	, 'rubro_id' =>	11	, 'nombre' => 'Ensayos']);
        Subrubro::create(['id' =>	31	, 'rubro_id' =>	11	, 'nombre' => 'Insumos']);
        Subrubro::create(['id' =>	32	, 'rubro_id' =>	11	, 'nombre' => 'Limpieza externa']);
        Subrubro::create(['id' =>	33	, 'rubro_id' =>	11	, 'nombre' => 'Limpieza química']);
        Subrubro::create(['id' =>	34	, 'rubro_id' =>	11	, 'nombre' => 'Montaje']);
        Subrubro::create(['id' =>	35	, 'rubro_id' =>	11	, 'nombre' => 'Quemadores']);
        Subrubro::create(['id' =>	36	, 'rubro_id' =>	11	, 'nombre' => 'Reparaciones - Mantenimiento']);
        Subrubro::create(['id' =>	37	, 'rubro_id' =>	12	, 'nombre' => 'Servicio']);
        Subrubro::create(['id' =>	38	, 'rubro_id' =>	13	, 'nombre' => 'Herramientas Office ']);
        Subrubro::create(['id' =>	39	, 'rubro_id' =>	13	, 'nombre' => 'SAP ']);
        Subrubro::create(['id' =>	40	, 'rubro_id' =>	13	, 'nombre' => 'Tributario ']);
        Subrubro::create(['id' =>	41	, 'rubro_id' =>	13	, 'nombre' => 'Contable']);
        Subrubro::create(['id' =>	42	, 'rubro_id' =>	13	, 'nombre' => 'Seguridad e Higiene']);
        Subrubro::create(['id' =>	43	, 'rubro_id' =>	13	, 'nombre' => 'Medio Ambiental ']);
        Subrubro::create(['id' =>	44	, 'rubro_id' =>	13	, 'nombre' => 'Comericio Exterior ']);
        Subrubro::create(['id' =>	45	, 'rubro_id' =>	13	, 'nombre' => 'Sueldos']);
        Subrubro::create(['id' =>	46	, 'rubro_id' =>	13	, 'nombre' => 'Ingeneria ']);
        Subrubro::create(['id' =>	47	, 'rubro_id' =>	13	, 'nombre' => 'Foguista ']);
        Subrubro::create(['id' =>	48	, 'rubro_id' =>	13	, 'nombre' => 'Coaching ']);
        Subrubro::create(['id' =>	49	, 'rubro_id' =>	13	, 'nombre' => 'Montador de carga (gruista)']);
        Subrubro::create(['id' =>	50	, 'rubro_id' =>	13	, 'nombre' => 'Capacitación PT15']);
        Subrubro::create(['id' =>	51	, 'rubro_id' =>	13	, 'nombre' => 'Orientadas al personal de mantenimiento y operaciones de las Centrales termoelectricas']);
        Subrubro::create(['id' =>	52	, 'rubro_id' =>	14	, 'nombre' => 'Carbones eléctricos']);
        Subrubro::create(['id' =>	53	, 'rubro_id' =>	14	, 'nombre' => 'Carbones mecánicos']);
        Subrubro::create(['id' =>	54	, 'rubro_id' =>	15	, 'nombre' => 'Servicios de lunch']);
        Subrubro::create(['id' =>	55	, 'rubro_id' =>	16	, 'nombre' => 'Mantenimiento o Reparaciones Civiles']);
        Subrubro::create(['id' =>	56	, 'rubro_id' =>	16	, 'nombre' => 'Mantenimiento o Reparaciones Mecánicas (metálicas)']);
        Subrubro::create(['id' =>	57	, 'rubro_id' =>	17	, 'nombre' => 'Calefactores industriales']);
        Subrubro::create(['id' =>	58	, 'rubro_id' =>	17	, 'nombre' => 'Ventiladores industriales']);
        Subrubro::create(['id' =>	59	, 'rubro_id' =>	18	, 'nombre' => 'Provisión']);
        Subrubro::create(['id' =>	60	, 'rubro_id' =>	18	, 'nombre' => 'Remetalados']);
        Subrubro::create(['id' =>	61	, 'rubro_id' =>	19	, 'nombre' => 'Gas Oil']);
        Subrubro::create(['id' =>	62	, 'rubro_id' =>	19	, 'nombre' => 'Fuel oil']);
        Subrubro::create(['id' =>	63	, 'rubro_id' =>	20	, 'nombre' => 'Compresor de Aire - Mantenimiento o Reparación']);
        Subrubro::create(['id' =>	64	, 'rubro_id' =>	20	, 'nombre' => 'Compresor de Aire - Montaje y puesta en servicio']);
        Subrubro::create(['id' =>	65	, 'rubro_id' =>	20	, 'nombre' => 'Compresor de Aire - Provisión']);
        Subrubro::create(['id' =>	66	, 'rubro_id' =>	20	, 'nombre' => 'Compresor de Aire - Repuestos e Insumos']);
        Subrubro::create(['id' =>	67	, 'rubro_id' =>	20	, 'nombre' => 'Compresor de Gas - Mantenimiento o Reparación']);
        Subrubro::create(['id' =>	68	, 'rubro_id' =>	20	, 'nombre' => 'Compresor de Gas - Montaje y puesta en servicio']);
        Subrubro::create(['id' =>	69	, 'rubro_id' =>	20	, 'nombre' => 'Compresor de Gas - Provisión']);
        Subrubro::create(['id' =>	70	, 'rubro_id' =>	20	, 'nombre' => 'Compresor de Gas - Repuestos e Insumos']);
        Subrubro::create(['id' =>	71	, 'rubro_id' =>	20	, 'nombre' => 'Compresor Neumático - Alquiler']);
        Subrubro::create(['id' =>	72	, 'rubro_id' =>	20	, 'nombre' => 'Compresor Neumático - Provisión']);
        Subrubro::create(['id' =>	73	, 'rubro_id' =>	21	, 'nombre' => 'Barra de cobre - Aislación']);
        Subrubro::create(['id' =>	74	, 'rubro_id' =>	21	, 'nombre' => 'Barra de cobre - Mecanizado']);
        Subrubro::create(['id' =>	75	, 'rubro_id' =>	21	, 'nombre' => 'Barra de cobre - Provisión']);
        Subrubro::create(['id' =>	76	, 'rubro_id' =>	21	, 'nombre' => 'Cable de automatización y comando - Provisión']);
        Subrubro::create(['id' =>	77	, 'rubro_id' =>	21	, 'nombre' => 'Cable de automatización y comando - Terminales, morsetería, bornes y accesorios']);
        Subrubro::create(['id' =>	78	, 'rubro_id' =>	21	, 'nombre' => 'Cable de potencia de BT - Empalme y Accesorios']);
        Subrubro::create(['id' =>	79	, 'rubro_id' =>	21	, 'nombre' => 'Cable de potencia de BT - Provisión']);
        Subrubro::create(['id' =>	80	, 'rubro_id' =>	21	, 'nombre' => 'Cable de potencia de BT - Terminal, morsetería y accesorios']);
        Subrubro::create(['id' =>	81	, 'rubro_id' =>	21	, 'nombre' => 'Cable desnudo Cu - Provisión']);
        Subrubro::create(['id' =>	82	, 'rubro_id' =>	21	, 'nombre' => 'Cable desnudo Cu - Terminal, morsetería, bornes y accesorios']);
        Subrubro::create(['id' =>	83	, 'rubro_id' =>	21	, 'nombre' => 'Cable flexible unipolar/bipolar/tripolar/tetrapolar de BT - Provisión']);
        Subrubro::create(['id' =>	84	, 'rubro_id' =>	21	, 'nombre' => 'Cable flexible unipolar/bipolar/tripolar/tetrapolar de BT - Terminal, morsetería, bornes y accesorios']);
        Subrubro::create(['id' =>	85	, 'rubro_id' =>	21	, 'nombre' => 'Cable para instrumentación electrónica (par-multipar-mallado) - Provisión']);
        Subrubro::create(['id' =>	86	, 'rubro_id' =>	21	, 'nombre' => 'Cable para instrumentación electrónica (par-multipar-mallado) - Terminal, morsetería, bornes y accesorios']);
        Subrubro::create(['id' =>	87	, 'rubro_id' =>	21	, 'nombre' => 'Cable para pirometría - Provisión']);
        Subrubro::create(['id' =>	88	, 'rubro_id' =>	21	, 'nombre' => 'Cable para pirometría - Terminales, morsetería, bornes y accesorios']);
        Subrubro::create(['id' =>	89	, 'rubro_id' =>	22	, 'nombre' => 'Servicio de consultoria - varios']);
        Subrubro::create(['id' =>	90	, 'rubro_id' =>	23	, 'nombre' => 'Control de plagas']);
        Subrubro::create(['id' =>	91	, 'rubro_id' =>	24	, 'nombre' => 'Correo Postal']);
        Subrubro::create(['id' =>	92	, 'rubro_id' =>	25	, 'nombre' => 'Declaración jurada de residuos']);
        Subrubro::create(['id' =>	93	, 'rubro_id' =>	26	, 'nombre' => 'Bateas de contención, pallets, paños absorbentes, Barreras absorbentes, insumos varios etc']);
        Subrubro::create(['id' =>	94	, 'rubro_id' =>	26	, 'nombre' => 'Estanterías, muebles']);
        Subrubro::create(['id' =>	95	, 'rubro_id' =>	27	, 'nombre' => 'Elementos de maniobra MT']);
        Subrubro::create(['id' =>	96	, 'rubro_id' =>	28	, 'nombre' => 'Calzado de seguridad  ']);
        Subrubro::create(['id' =>	97	, 'rubro_id' =>	28	, 'nombre' => 'Elementos de seguridad para Izaje (malacate, aparejo, arnés, etc.)  ']);
        Subrubro::create(['id' =>	98	, 'rubro_id' =>	29	, 'nombre' => 'Embragues y frenos industriales']);
        Subrubro::create(['id' =>	99	, 'rubro_id' =>	30	, 'nombre' => 'Empaquetaduras']);
        Subrubro::create(['id' =>	100	, 'rubro_id' =>	31	, 'nombre' => 'Ensayos de aparatos sometidos a presión c/s fuego y calibración de válvulas']);
        Subrubro::create(['id' =>	101	, 'rubro_id' =>	31	, 'nombre' => 'Ensayos eléctricos']);
        Subrubro::create(['id' =>	102	, 'rubro_id' =>	31	, 'nombre' => 'Ensayos No Destructivos (END)']);
        Subrubro::create(['id' =>	103	, 'rubro_id' =>	31	, 'nombre' => 'Ensayos químicos de líquido espumígeno ']);
        Subrubro::create(['id' =>	104	, 'rubro_id' =>	31	, 'nombre' => 'Ensayos térmicos']);
        Subrubro::create(['id' =>	105	, 'rubro_id' =>	32	, 'nombre' => 'Electrónico (Osciloscopio - Transductores) - Provisión']);
        Subrubro::create(['id' =>	106	, 'rubro_id' =>	32	, 'nombre' => 'Electrónico (Osciloscopio - Transductores) - Reparación']);
        Subrubro::create(['id' =>	107	, 'rubro_id' =>	32	, 'nombre' => 'Equipo de Mantenimiento y Control de Calidad (Videoscopio - Espesor - Vibraciones - Otros) - Ensayos y Certificación']);
        Subrubro::create(['id' =>	108	, 'rubro_id' =>	32	, 'nombre' => 'Equipo de Mantenimiento y Control de Calidad (Videoscopio - Espesor - Vibraciones - Otros) - Provisión']);
        Subrubro::create(['id' =>	109	, 'rubro_id' =>	32	, 'nombre' => 'Equipo de Mantenimiento y Control de Calidad (Videoscopio - Espesor - Vibraciones - Otros) - Reparación']);
        Subrubro::create(['id' =>	110	, 'rubro_id' =>	32	, 'nombre' => 'Equipo de Medición de Construcción (niveles - teodolitos - otros) - Provisión']);
        Subrubro::create(['id' =>	111	, 'rubro_id' =>	32	, 'nombre' => 'Humedad (Higrómetro - Hidrotermógrafo) - Certificación']);
        Subrubro::create(['id' =>	112	, 'rubro_id' =>	32	, 'nombre' => 'Humedad (Higrómetro - Hidrotermógrafo) - Provisión']);
        Subrubro::create(['id' =>	113	, 'rubro_id' =>	32	, 'nombre' => 'Humedad (Higrómetro - Hidrotermógrafo) - Reparación']);
        Subrubro::create(['id' =>	114	, 'rubro_id' =>	32	, 'nombre' => 'Longitud (odómetros - cintas métricas) - Provisión']);
        Subrubro::create(['id' =>	115	, 'rubro_id' =>	32	, 'nombre' => 'Mantenimiento Mecánico (Calibres - Micrómetros - Reglas/Escuadras - Goniómetro - Niveles - Roscas - Compás) - Provisión']);
        Subrubro::create(['id' =>	116	, 'rubro_id' =>	32	, 'nombre' => 'Masa (Balanza - Báscula - Espectrómetro) - Ensayos y Certificación']);
        Subrubro::create(['id' =>	117	, 'rubro_id' =>	32	, 'nombre' => 'Masa (Balanza - Báscula - Espectrómetro) - Provisión']);
        Subrubro::create(['id' =>	118	, 'rubro_id' =>	32	, 'nombre' => 'Masa (Balanza - Báscula - Espectrómetro) - Reparación']);
        Subrubro::create(['id' =>	119	, 'rubro_id' =>	32	, 'nombre' => 'Ópticos - Ensayos y Certificación']);
        Subrubro::create(['id' =>	120	, 'rubro_id' =>	32	, 'nombre' => 'Ópticos - Provisión']);
        Subrubro::create(['id' =>	121	, 'rubro_id' =>	32	, 'nombre' => 'Ópticos - Reparación']);
        Subrubro::create(['id' =>	122	, 'rubro_id' =>	32	, 'nombre' => 'Otros - Provisión']);
        Subrubro::create(['id' =>	123	, 'rubro_id' =>	32	, 'nombre' => 'Parámetros Eléctricos (Tensión - Corriente - Resistencia - Potencia activa - Potencia reactiva - Energía - Frecuencia - cos fi) - Ensayos y Certificación']);
        Subrubro::create(['id' =>	124	, 'rubro_id' =>	32	, 'nombre' => 'Parámetros Eléctricos (Tensión - Corriente - Resistencia - Potencia activa - Potencia reactiva - Energía - Frecuencia - cos fi) - Provisión']);
        Subrubro::create(['id' =>	125	, 'rubro_id' =>	32	, 'nombre' => 'Parámetros Eléctricos (Tensión - Corriente - Resistencia - Potencia activa - Potencia reactiva - Energía - Frecuencia - cos fi) - Reparación']);
        Subrubro::create(['id' =>	126	, 'rubro_id' =>	32	, 'nombre' => 'Presión (Manómetro - Barómetro - Vacuómetro - Transductor - Transmisor) - Reparación']);
        Subrubro::create(['id' =>	127	, 'rubro_id' =>	32	, 'nombre' => 'Presión (Manómetro - Barómetro - Vacuómetro - Transductor) - Ensayos y Certificación']);
        Subrubro::create(['id' =>	128	, 'rubro_id' =>	32	, 'nombre' => 'Presión (Manómetro - Barómetro - Vacuómetro - Transductor-Transmisor) - Provisión']);
        Subrubro::create(['id' =>	129	, 'rubro_id' =>	32	, 'nombre' => 'Temperatura (Termómetro - Pirómetro y Cámara Infrarroja - Termocupla) - Ensayos y Certificación']);
        Subrubro::create(['id' =>	130	, 'rubro_id' =>	32	, 'nombre' => 'Temperatura (Termómetro - Pirómetro y Cámara Infrarroja - Termocupla) - Provisión']);
        Subrubro::create(['id' =>	131	, 'rubro_id' =>	32	, 'nombre' => 'Temperatura (Termómetro - Pirómetro y Cámara Infrarroja - Termocupla) - Reparación']);
        Subrubro::create(['id' =>	132	, 'rubro_id' =>	32	, 'nombre' => 'Climatológico (Estación Meteorológica, Anemómetro) - Ensayos y Certificación']);
        Subrubro::create(['id' =>	133	, 'rubro_id' =>	32	, 'nombre' => 'Climatológico (Estación Meteorológica, Anemómetro) - Provisión']);
        Subrubro::create(['id' =>	134	, 'rubro_id' =>	32	, 'nombre' => 'Climatológico (Estación Meteorológica, Anemómetro) - Reparación']);
        Subrubro::create(['id' =>	135	, 'rubro_id' =>	32	, 'nombre' => 'Medio Ambiente (Ruido - Emisión de Gases - Emisión de Material Particulado - Campo eléctrico y magnético - Radio interferencias) - Ensayos, calibracion y Certificación ']);
        Subrubro::create(['id' =>	136	, 'rubro_id' =>	32	, 'nombre' => 'Medio Ambiente (Ruido - Emisión de Gases - Emisión de Material Particulado - Campo eléctrico y magnético - Radio interferencias) - Provisión de equipo y repuestos']);
        Subrubro::create(['id' =>	137	, 'rubro_id' =>	32	, 'nombre' => 'Medio Ambiente (Ruido - Emisión de Gases - Emisión de Material Particulado - Campo eléctrico y magnético - Radio interferencias) - Reparación']);
        Subrubro::create(['id' =>	138	, 'rubro_id' =>	32	, 'nombre' => 'Seguridad e Higiene (Luxómetro - Resistencia puesta a tierra - Fuga de gases - etc.) - Ensayos y Certificación']);
        Subrubro::create(['id' =>	139	, 'rubro_id' =>	32	, 'nombre' => 'Seguridad e Higiene (Luxómetro - Resistencia puesta a tierra - Fuga de gases - etc.) - Provisión']);
        Subrubro::create(['id' =>	140	, 'rubro_id' =>	32	, 'nombre' => 'Seguridad e Higiene (Luxómetro - Resistencia puesta a tierra - Fuga de gases - etc.) - Reparación y  Calibracion']);
        Subrubro::create(['id' =>	141	, 'rubro_id' =>	32	, 'nombre' => 'Seguridad Eléctrica (Detector de tensión - Secuencia de fase - otros) - Ensayos y Certificación']);
        Subrubro::create(['id' =>	142	, 'rubro_id' =>	32	, 'nombre' => 'Seguridad Eléctrica (Detector de tensión - Secuencia de fase - otros) - Provisión']);
        Subrubro::create(['id' =>	143	, 'rubro_id' =>	32	, 'nombre' => 'Seguridad Eléctrica (Detector de tensión - Secuencia de fase - otros) - Reparación']);
        Subrubro::create(['id' =>	144	, 'rubro_id' =>	33	, 'nombre' => 'Alta tensión (132kv) - Diagnóstico y ensayos']);
        Subrubro::create(['id' =>	145	, 'rubro_id' =>	33	, 'nombre' => 'Alta tensión (132kv) - Insumos especiales']);
        Subrubro::create(['id' =>	146	, 'rubro_id' =>	33	, 'nombre' => 'Alta tensión (132kv) - Provisión equipos']);
        Subrubro::create(['id' =>	147	, 'rubro_id' =>	33	, 'nombre' => 'Alta tensión (132kv) - Repuestos']);
        Subrubro::create(['id' =>	148	, 'rubro_id' =>	33	, 'nombre' => 'Alta tensión (132kv) - Servicios de Mantenimiento']);
        Subrubro::create(['id' =>	149	, 'rubro_id' =>	33	, 'nombre' => 'Media tensión (13,2kv / 11,5 Kv) - Diagnóstico y ensayos']);
        Subrubro::create(['id' =>	150	, 'rubro_id' =>	33	, 'nombre' => 'Media tensión (13,2kv / 11,5 Kv) - Insumos especiales']);
        Subrubro::create(['id' =>	151	, 'rubro_id' =>	33	, 'nombre' => 'Media tensión (13,2kv / 11,5 Kv) - Provisión equipos']);
        Subrubro::create(['id' =>	152	, 'rubro_id' =>	33	, 'nombre' => 'Media tensión (13,2kv / 11,5 Kv) - Repuestos']);
        Subrubro::create(['id' =>	153	, 'rubro_id' =>	33	, 'nombre' => 'Media tensión (13,2kv / 11,5 Kv) - Servicios de Mantenimiento']);
        Subrubro::create(['id' =>	154	, 'rubro_id' =>	33	, 'nombre' => 'Electrónicos varios']);
        Subrubro::create(['id' =>	155	, 'rubro_id' =>	34	, 'nombre' => 'Estudio de impacto ambiental']);
        Subrubro::create(['id' =>	156	, 'rubro_id' =>	34	, 'nombre' => 'Estudio de impacto ambiental atmosférico']);
        Subrubro::create(['id' =>	157	, 'rubro_id' =>	34	, 'nombre' => 'Estudio de suelos']);
        Subrubro::create(['id' =>	158	, 'rubro_id' =>	34	, 'nombre' => 'Estudio hidrogeológico']);
        Subrubro::create(['id' =>	159	, 'rubro_id' =>	35	, 'nombre' => 'Boquillas para mangueras incendio - Provisión']);
        Subrubro::create(['id' =>	160	, 'rubro_id' =>	35	, 'nombre' => 'Extintores y Tubos CO2 - Provisión, Servicio y Mantenimiento']);
        Subrubro::create(['id' =>	161	, 'rubro_id' =>	35	, 'nombre' => 'Liquido espumígeno - Análisis ']);
        Subrubro::create(['id' =>	162	, 'rubro_id' =>	35	, 'nombre' => 'Liquido espumígeno - Provisión']);
        Subrubro::create(['id' =>	163	, 'rubro_id' =>	35	, 'nombre' => 'Mangueras para red incendio - Provisión']);
        Subrubro::create(['id' =>	164	, 'rubro_id' =>	35	, 'nombre' => 'Matafuego de Mano - Provisión']);
        Subrubro::create(['id' =>	165	, 'rubro_id' =>	35	, 'nombre' => 'Matafuego de Mano - Recarga']);
        Subrubro::create(['id' =>	166	, 'rubro_id' =>	35	, 'nombre' => 'Matafuego Estación fija - Provisión ']);
        Subrubro::create(['id' =>	167	, 'rubro_id' =>	35	, 'nombre' => 'Matafuego Estación fija - Recarga y mantenimiento']);
        Subrubro::create(['id' =>	168	, 'rubro_id' =>	35	, 'nombre' => 'Monitores de red Incendio - Mantenimiento']);
        Subrubro::create(['id' =>	169	, 'rubro_id' =>	36	, 'nombre' => 'Abrasivos (lijas - discos - cintas - tela esmeril - ruedas - superabrasivos)']);
        Subrubro::create(['id' =>	170	, 'rubro_id' =>	36	, 'nombre' => 'Adhesivos (pegamentos - activadores - siliconas)']);
        Subrubro::create(['id' =>	171	, 'rubro_id' =>	36	, 'nombre' => 'Bancos de trabajo']);
        Subrubro::create(['id' =>	172	, 'rubro_id' =>	36	, 'nombre' => 'Bateas lava piezas']);
        Subrubro::create(['id' =>	173	, 'rubro_id' =>	36	, 'nombre' => 'Bulonería (accesorios - bulones - tuercas - tornillos - varillas)']);
        Subrubro::create(['id' =>	174	, 'rubro_id' =>	36	, 'nombre' => 'Calefactores']);
        Subrubro::create(['id' =>	175	, 'rubro_id' =>	36	, 'nombre' => 'Cargadores y arrancadores']);
        Subrubro::create(['id' =>	176	, 'rubro_id' =>	36	, 'nombre' => 'Cepillos industriales']);
        Subrubro::create(['id' =>	177	, 'rubro_id' =>	36	, 'nombre' => 'Cerrajería y herrajes']);
        Subrubro::create(['id' =>	178	, 'rubro_id' =>	36	, 'nombre' => 'Cintas adhesivas']);
        Subrubro::create(['id' =>	179	, 'rubro_id' =>	36	, 'nombre' => 'Consumibles']);
        Subrubro::create(['id' =>	180	, 'rubro_id' =>	36	, 'nombre' => 'Fijaciones (mecánicas - químicas)']);
        Subrubro::create(['id' =>	181	, 'rubro_id' =>	36	, 'nombre' => 'Gomas (burletes - anti vibratorios - arandelas)']);
        Subrubro::create(['id' =>	182	, 'rubro_id' =>	36	, 'nombre' => 'Herramientas a batería']);
        Subrubro::create(['id' =>	183	, 'rubro_id' =>	36	, 'nombre' => 'Herramientas a explosión']);
        Subrubro::create(['id' =>	184	, 'rubro_id' =>	36	, 'nombre' => 'Herramientas de construcción']);
        Subrubro::create(['id' =>	185	, 'rubro_id' =>	36	, 'nombre' => 'Herramientas de corte y roscado']);
        Subrubro::create(['id' =>	186	, 'rubro_id' =>	36	, 'nombre' => 'Herramientas de limpieza e higiene']);
        Subrubro::create(['id' =>	187	, 'rubro_id' =>	36	, 'nombre' => 'Herramientas de medición y trazado']);
        Subrubro::create(['id' =>	188	, 'rubro_id' =>	36	, 'nombre' => 'Herramientas Eléctricas']);
        Subrubro::create(['id' =>	189	, 'rubro_id' =>	36	, 'nombre' => 'Herramientas eléctricas']);
        Subrubro::create(['id' =>	190	, 'rubro_id' =>	36	, 'nombre' => 'Herramientas jardinería']);
        Subrubro::create(['id' =>	191	, 'rubro_id' =>	36	, 'nombre' => 'Herramientas Manuales']);
        Subrubro::create(['id' =>	192	, 'rubro_id' =>	36	, 'nombre' => 'Herramientas manuales']);
        Subrubro::create(['id' =>	193	, 'rubro_id' =>	36	, 'nombre' => 'Herramientas neumáticas']);
        Subrubro::create(['id' =>	194	, 'rubro_id' =>	36	, 'nombre' => 'Insumos varios']);
        Subrubro::create(['id' =>	195	, 'rubro_id' =>	36	, 'nombre' => 'Máquinas de banco y pie']);
        Subrubro::create(['id' =>	196	, 'rubro_id' =>	36	, 'nombre' => 'Morsas']);
        Subrubro::create(['id' =>	197	, 'rubro_id' =>	36	, 'nombre' => 'Organizadores de herramientas']);
        Subrubro::create(['id' =>	198	, 'rubro_id' =>	36	, 'nombre' => 'Pinturería (herramientas - insumos)']);
        Subrubro::create(['id' =>	199	, 'rubro_id' =>	36	, 'nombre' => 'Refrigeración (herramientas - insumos)']);
        Subrubro::create(['id' =>	200	, 'rubro_id' =>	36	, 'nombre' => 'Selladores']);
        Subrubro::create(['id' =>	201	, 'rubro_id' =>	36	, 'nombre' => 'Soldadura (equipos, accesorios e insumos)']);
        Subrubro::create(['id' =>	202	, 'rubro_id' =>	36	, 'nombre' => 'Transmisiones y acoplamientos (correas - medias mallas - uniones - poleas - piñones)']);
        Subrubro::create(['id' =>	203	, 'rubro_id' =>	36	, 'nombre' => 'Lavaojos (lavaojos, duchas, etc no corresponden a este rubro)']);
        Subrubro::create(['id' =>	204	, 'rubro_id' =>	37	, 'nombre' => 'Aceite']);
        Subrubro::create(['id' =>	205	, 'rubro_id' =>	37	, 'nombre' => 'Aire']);
        Subrubro::create(['id' =>	206	, 'rubro_id' =>	37	, 'nombre' => 'Gas Natural']);
        Subrubro::create(['id' =>	207	, 'rubro_id' =>	37	, 'nombre' => 'Gases']);
        Subrubro::create(['id' =>	208	, 'rubro_id' =>	37	, 'nombre' => 'Hidrocarburos']);
        Subrubro::create(['id' =>	209	, 'rubro_id' =>	37	, 'nombre' => 'Planta DEMI']);
        Subrubro::create(['id' =>	210	, 'rubro_id' =>	38	, 'nombre' => 'Fundición y fabricación Cojinetes']);
        Subrubro::create(['id' =>	211	, 'rubro_id' =>	38	, 'nombre' => 'Fundiciones generales']);
        Subrubro::create(['id' =>	212	, 'rubro_id' =>	38	, 'nombre' => 'Montajes metalúrgicos']);
        Subrubro::create(['id' =>	213	, 'rubro_id' =>	39	, 'nombre' => 'Acetileno']);
        Subrubro::create(['id' =>	214	, 'rubro_id' =>	39	, 'nombre' => 'Argón']);
        Subrubro::create(['id' =>	215	, 'rubro_id' =>	39	, 'nombre' => 'Dióxido de carbono']);
        Subrubro::create(['id' =>	216	, 'rubro_id' =>	39	, 'nombre' => 'Freón']);
        Subrubro::create(['id' =>	217	, 'rubro_id' =>	39	, 'nombre' => 'Gases patrón para calibración de equipos de medición de efluentes gaseosos']);
        Subrubro::create(['id' =>	218	, 'rubro_id' =>	39	, 'nombre' => 'Helio']);
        Subrubro::create(['id' =>	219	, 'rubro_id' =>	39	, 'nombre' => 'Hidrógeno']);
        Subrubro::create(['id' =>	220	, 'rubro_id' =>	39	, 'nombre' => 'Nitrógeno']);
        Subrubro::create(['id' =>	221	, 'rubro_id' =>	39	, 'nombre' => 'Oxígeno']);
        Subrubro::create(['id' =>	222	, 'rubro_id' =>	39	, 'nombre' => 'NO concentración aprox. 200 ppm. Balance nitrógeno']);
        Subrubro::create(['id' =>	223	, 'rubro_id' =>	39	, 'nombre' => 'NO2 concentración aprox. 200 ppm. Balance nitrógeno']);
        Subrubro::create(['id' =>	224	, 'rubro_id' =>	39	, 'nombre' => 'O2 concentración aprox. 3 %, CO concentración aprox.  100 ppm, SO2 concentración aprox. 200 ppm. Balance nitrógeno']);
        Subrubro::create(['id' =>	225	, 'rubro_id' =>	39	, 'nombre' => 'NO concentración aprox. 45 ppm. + CO concentracion aprox. 45 ppm. Balance nitrógeno']);
        Subrubro::create(['id' =>	226	, 'rubro_id' =>	39	, 'nombre' => 'NO2 concentración aprox. 45 ppm. Balance nitrógeno']);
        Subrubro::create(['id' =>	227	, 'rubro_id' =>	39	, 'nombre' => 'SO2 concentración aprox. 45 ppm. Balance nitrógeno']);
        Subrubro::create(['id' =>	228	, 'rubro_id' =>	40	, 'nombre' => 'Ensayos']);
        Subrubro::create(['id' =>	229	, 'rubro_id' =>	40	, 'nombre' => 'Mantenimiento o Reparación']);
        Subrubro::create(['id' =>	230	, 'rubro_id' =>	41	, 'nombre' => 'Grupo electrógeno con carro (mediana potencia) - Alquiler']);
        Subrubro::create(['id' =>	231	, 'rubro_id' =>	41	, 'nombre' => 'Grupo electrógeno con carro (mediana potencia) - Mantenimiento']);
        Subrubro::create(['id' =>	232	, 'rubro_id' =>	41	, 'nombre' => 'Grupo electrógeno con carro (mediana potencia) - Provisión']);
        Subrubro::create(['id' =>	233	, 'rubro_id' =>	41	, 'nombre' => 'Grupo electrógeno con carro (mediana potencia) - Repuestos y consumibles']);
        Subrubro::create(['id' =>	234	, 'rubro_id' =>	41	, 'nombre' => 'Grupo electrógeno en trineo (alta potencia) - Alquiler']);
        Subrubro::create(['id' =>	235	, 'rubro_id' =>	41	, 'nombre' => 'Grupo electrógeno en trineo (alta potencia) - Mantenimiento']);
        Subrubro::create(['id' =>	236	, 'rubro_id' =>	41	, 'nombre' => 'Grupo electrógeno en trineo (alta potencia) - Provisión']);
        Subrubro::create(['id' =>	237	, 'rubro_id' =>	41	, 'nombre' => 'Grupo electrógeno en trineo (alta potencia) - Repuestos y consumibles']);
        Subrubro::create(['id' =>	238	, 'rubro_id' =>	41	, 'nombre' => 'Grupo electrógeno portátil (baja potencia) - Alquiler']);
        Subrubro::create(['id' =>	239	, 'rubro_id' =>	41	, 'nombre' => 'Grupo electrógeno portátil (baja potencia) - Mantenimiento']);
        Subrubro::create(['id' =>	240	, 'rubro_id' =>	41	, 'nombre' => 'Grupo electrógeno portátil (baja potencia) - Provisión']);
        Subrubro::create(['id' =>	241	, 'rubro_id' =>	41	, 'nombre' => 'Grupo electrógeno portátil (baja potencia) - Repuestos y consumibles']);
        Subrubro::create(['id' =>	242	, 'rubro_id' =>	42	, 'nombre' => 'Repuestos']);
        Subrubro::create(['id' =>	243	, 'rubro_id' =>	42	, 'nombre' => 'Herramiientas']);
        Subrubro::create(['id' =>	244	, 'rubro_id' =>	43	, 'nombre' => 'Médicos']);
        Subrubro::create(['id' =>	245	, 'rubro_id' =>	43	, 'nombre' => 'Actuarios']);
        Subrubro::create(['id' =>	246	, 'rubro_id' =>	43	, 'nombre' => 'Despachante de Aduana']);
        Subrubro::create(['id' =>	247	, 'rubro_id' =>	43	, 'nombre' => 'Escribanos ']);
        Subrubro::create(['id' =>	248	, 'rubro_id' =>	43	, 'nombre' => 'Impositivos ']);
        Subrubro::create(['id' =>	249	, 'rubro_id' =>	43	, 'nombre' => 'Legales']);
        Subrubro::create(['id' =>	250	, 'rubro_id' =>	43	, 'nombre' => 'Traductores']);
        Subrubro::create(['id' =>	251	, 'rubro_id' =>	44	, 'nombre' => 'Accesorio para lámpara bajo consumo (transformador, balasto, arrancador, zócalo, portalámpara, etc.)']);
        Subrubro::create(['id' =>	252	, 'rubro_id' =>	44	, 'nombre' => 'Accesorio para lámpara fluorescente (transformador, balasto, arrancador, zócalo, capacitor, portalámpara, borneras, etc.)']);
        Subrubro::create(['id' =>	253	, 'rubro_id' =>	44	, 'nombre' => 'Accesorio para lámpara halógena (transformador, portalámpara, zócalo, etc.)']);
        Subrubro::create(['id' =>	254	, 'rubro_id' =>	44	, 'nombre' => 'Accesorio para lámpara incandescente (portalámpara)']);
        Subrubro::create(['id' =>	255	, 'rubro_id' =>	44	, 'nombre' => 'Accesorio para lámpara led (transformador, portalámpara, zócalo)']);
        Subrubro::create(['id' =>	256	, 'rubro_id' =>	44	, 'nombre' => 'Artefacto de Iluminación Antiexplosivo - Montaje']);
        Subrubro::create(['id' =>	257	, 'rubro_id' =>	44	, 'nombre' => 'Artefacto de Iluminación Antiexplosivo - Provisión']);
        Subrubro::create(['id' =>	258	, 'rubro_id' =>	44	, 'nombre' => 'Artefacto de Iluminación Exterior Columna - Accesorios (cajas de conexión, borneras, fusibles, puesta a tierra, etc.)']);
        Subrubro::create(['id' =>	259	, 'rubro_id' =>	44	, 'nombre' => 'Artefacto de Iluminación Exterior Columna - Mantenimiento']);
        Subrubro::create(['id' =>	260	, 'rubro_id' =>	44	, 'nombre' => 'Artefacto de Iluminación Exterior Columna - Montaje']);
        Subrubro::create(['id' =>	261	, 'rubro_id' =>	44	, 'nombre' => 'Artefacto de Iluminación Exterior Columna - Provisión']);
        Subrubro::create(['id' =>	262	, 'rubro_id' =>	44	, 'nombre' => 'Artefacto de Iluminación Exterior Proyector - Mantenimiento']);
        Subrubro::create(['id' =>	263	, 'rubro_id' =>	44	, 'nombre' => 'Artefacto de Iluminación Exterior Proyector - Montaje']);
        Subrubro::create(['id' =>	264	, 'rubro_id' =>	44	, 'nombre' => 'Artefacto de Iluminación Exterior Proyector - Provisión']);
        Subrubro::create(['id' =>	265	, 'rubro_id' =>	44	, 'nombre' => 'Artefacto de Iluminación Interior - Montaje']);
        Subrubro::create(['id' =>	266	, 'rubro_id' =>	44	, 'nombre' => 'Artefacto de Iluminación Interior - Provisión']);
        Subrubro::create(['id' =>	267	, 'rubro_id' =>	44	, 'nombre' => 'Fotocélula']);
        Subrubro::create(['id' =>	268	, 'rubro_id' =>	44	, 'nombre' => 'Lámpara bajo consumo - Provisión']);
        Subrubro::create(['id' =>	269	, 'rubro_id' =>	44	, 'nombre' => 'Lámpara fluorescente - Provisión']);
        Subrubro::create(['id' =>	270	, 'rubro_id' =>	44	, 'nombre' => 'Lámpara halógena - Provisión']);
        Subrubro::create(['id' =>	271	, 'rubro_id' =>	44	, 'nombre' => 'Lámpara incandescente - Provisión']);
        Subrubro::create(['id' =>	272	, 'rubro_id' =>	44	, 'nombre' => 'Lámpara led - Provisión']);
        Subrubro::create(['id' =>	273	, 'rubro_id' =>	45	, 'nombre' => 'Equipos A/C - Insumos o Repuestos']);
        Subrubro::create(['id' =>	274	, 'rubro_id' =>	45	, 'nombre' => 'Equipos A/C - Montaje']);
        Subrubro::create(['id' =>	275	, 'rubro_id' =>	45	, 'nombre' => 'Equipos A/C - Provisión']);
        Subrubro::create(['id' =>	276	, 'rubro_id' =>	45	, 'nombre' => 'Equipos A/C - Reparación']);
        Subrubro::create(['id' =>	277	, 'rubro_id' =>	45	, 'nombre' => 'Equipos de intercambio de calor - Insumos o Elementos']);
        Subrubro::create(['id' =>	278	, 'rubro_id' =>	45	, 'nombre' => 'Equipos de intercambio de calor - Mantenimiento o Reparación']);
        Subrubro::create(['id' =>	279	, 'rubro_id' =>	45	, 'nombre' => 'Equipos de intercambio de calor - Montaje']);
        Subrubro::create(['id' =>	280	, 'rubro_id' =>	45	, 'nombre' => 'Equipos de intercambio de calor - Provisión']);
        Subrubro::create(['id' =>	281	, 'rubro_id' =>	45	, 'nombre' => 'Radiadores industriales - Insumos o Repuestos']);
        Subrubro::create(['id' =>	282	, 'rubro_id' =>	45	, 'nombre' => 'Radiadores industriales - Mantenimiento o Reparación']);
        Subrubro::create(['id' =>	283	, 'rubro_id' =>	45	, 'nombre' => 'Radiadores industriales - Montaje']);
        Subrubro::create(['id' =>	284	, 'rubro_id' =>	45	, 'nombre' => 'Radiadores Industriales - Provisión']);
        Subrubro::create(['id' =>	285	, 'rubro_id' =>	46	, 'nombre' => 'Análisis Eléctricos']);
        Subrubro::create(['id' =>	286	, 'rubro_id' =>	46	, 'nombre' => 'Análisis Mecánicos']);
        Subrubro::create(['id' =>	287	, 'rubro_id' =>	46	, 'nombre' => 'Análisis Químicos']);
        Subrubro::create(['id' =>	288	, 'rubro_id' =>	47	, 'nombre' => 'Artículos de Librería']);
        Subrubro::create(['id' =>	289	, 'rubro_id' =>	48	, 'nombre' => 'Equipos de limpieza industrial']);
        Subrubro::create(['id' =>	290	, 'rubro_id' =>	48	, 'nombre' => 'Insumos de limpieza industrial']);
        Subrubro::create(['id' =>	291	, 'rubro_id' =>	48	, 'nombre' => 'Limpieza de Áreas Verdes']);
        Subrubro::create(['id' =>	292	, 'rubro_id' =>	48	, 'nombre' => 'Limpieza de Canales']);
        Subrubro::create(['id' =>	293	, 'rubro_id' =>	48	, 'nombre' => 'Limpieza de Edificios']);
        Subrubro::create(['id' =>	294	, 'rubro_id' =>	48	, 'nombre' => 'Limpieza de Maquinarias e Instalaciones de proceso']);
        Subrubro::create(['id' =>	295	, 'rubro_id' =>	48	, 'nombre' => 'Limpieza Viales']);
        Subrubro::create(['id' =>	296	, 'rubro_id' =>	49	, 'nombre' => 'Provisión']);
        Subrubro::create(['id' =>	297	, 'rubro_id' =>	50	, 'nombre' => 'Construcciones metalúrgicas - Estructuras']);
        Subrubro::create(['id' =>	298	, 'rubro_id' =>	50	, 'nombre' => 'Construcciones metalúrgicas - Fundiciones cojinetes']);
        Subrubro::create(['id' =>	299	, 'rubro_id' =>	50	, 'nombre' => 'Construcciones metalúrgicas - Fundiciones generales']);
        Subrubro::create(['id' =>	300	, 'rubro_id' =>	50	, 'nombre' => 'Construcciones metalúrgicas - Partes Generales']);
        Subrubro::create(['id' =>	301	, 'rubro_id' =>	50	, 'nombre' => 'Construcciones metalúrgicas - Repuestos Turbinas']);
        Subrubro::create(['id' =>	302	, 'rubro_id' =>	50	, 'nombre' => 'Corte - Corte Chorro de Agua']);
        Subrubro::create(['id' =>	303	, 'rubro_id' =>	50	, 'nombre' => 'Corte - Corte Laser']);
        Subrubro::create(['id' =>	304	, 'rubro_id' =>	50	, 'nombre' => 'Corte - Corte Plasma']);
        Subrubro::create(['id' =>	305	, 'rubro_id' =>	50	, 'nombre' => 'Mecanizado de Piezas - Aporte de Cromo']);
        Subrubro::create(['id' =>	306	, 'rubro_id' =>	50	, 'nombre' => 'Mecanizado de Piezas - Engranajes']);
        Subrubro::create(['id' =>	307	, 'rubro_id' =>	50	, 'nombre' => 'Mecanizado de Piezas - General']);
        Subrubro::create(['id' =>	308	, 'rubro_id' =>	50	, 'nombre' => 'Mecanizado de Piezas - Precisión']);
        Subrubro::create(['id' =>	309	, 'rubro_id' =>	50	, 'nombre' => 'Mecanizado de Piezas - Rectificado']);
        Subrubro::create(['id' =>	310	, 'rubro_id' =>	50	, 'nombre' => 'Mecanizado de Piezas - Tornería']);
        Subrubro::create(['id' =>	311	, 'rubro_id' =>	50	, 'nombre' => 'Mecanizados Generales']);
        Subrubro::create(['id' =>	312	, 'rubro_id' =>	51	, 'nombre' => 'Botiquín elementos']);
        Subrubro::create(['id' =>	313	, 'rubro_id' =>	51	, 'nombre' => 'Vacunas']);
        Subrubro::create(['id' =>	314	, 'rubro_id' =>	51	, 'nombre' => 'Parches DEA']);
        Subrubro::create(['id' =>	315	, 'rubro_id' =>	52	, 'nombre' => 'Sillas de Rueda, muñero RCP, etc.']);
        Subrubro::create(['id' =>	316	, 'rubro_id' =>	53	, 'nombre' => 'Exámenes médicos']);
        Subrubro::create(['id' =>	317	, 'rubro_id' =>	53	, 'nombre' => 'Control de ausentismo']);
        Subrubro::create(['id' =>	318	, 'rubro_id' =>	53	, 'nombre' => 'Servicio de emergencia médica/área protegida']);
        Subrubro::create(['id' =>	319	, 'rubro_id' =>	53	, 'nombre' => 'Retiro y Disposición Final Residuos Patogenicos']);
        Subrubro::create(['id' =>	320	, 'rubro_id' =>	54	, 'nombre' => 'Aparejos y accesorios. ']);
        Subrubro::create(['id' =>	321	, 'rubro_id' =>	54	, 'nombre' => 'Autoelevadores (Provisión - Alquiler - Repuestos - Mantenimiento)']);
        Subrubro::create(['id' =>	322	, 'rubro_id' =>	54	, 'nombre' => 'Certificación de equipos de elevación. ']);
        Subrubro::create(['id' =>	323	, 'rubro_id' =>	54	, 'nombre' => 'Certificación de equipos de izaje. ']);
        Subrubro::create(['id' =>	324	, 'rubro_id' =>	54	, 'nombre' => 'Equipo de sujeción (fajas) con criquet y gancho']);
        Subrubro::create(['id' =>	325	, 'rubro_id' =>	54	, 'nombre' => 'Equipos de arrastre de cargas (Provisión - Alquiler - Repuestos - Mantenimiento)']);
        Subrubro::create(['id' =>	326	, 'rubro_id' =>	54	, 'nombre' => 'Equipos de elevación y cargas livianas (Provisión - Alquiler - Repuestos - Mantenimiento)']);
        Subrubro::create(['id' =>	327	, 'rubro_id' =>	54	, 'nombre' => 'Escalera (articulada - simple y tijera - extensible)']);
        Subrubro::create(['id' =>	328	, 'rubro_id' =>	54	, 'nombre' => 'Escalera dieléctrica']);
        Subrubro::create(['id' =>	329	, 'rubro_id' =>	54	, 'nombre' => 'Escaleras especiales']);
        Subrubro::create(['id' =>	330	, 'rubro_id' =>	54	, 'nombre' => 'Eslingas (incluye ganchos, uniones y accesorios).']);
        Subrubro::create(['id' =>	331	, 'rubro_id' =>	54	, 'nombre' => 'Hidroelevador (Provisión - Alquiler - Repuestos - Mantenimiento)']);
        Subrubro::create(['id' =>	332	, 'rubro_id' =>	54	, 'nombre' => 'Hidrogrúa (Provisión - Alquiler - Repuestos - Mantenimiento)']);
        Subrubro::create(['id' =>	333	, 'rubro_id' =>	54	, 'nombre' => 'Malacates y accesorios']);
        Subrubro::create(['id' =>	334	, 'rubro_id' =>	54	, 'nombre' => 'Plataformas elevadoras fijas y articuladas (Provisión - Alquiler - Repuestos - Mantenimiento)']);
        Subrubro::create(['id' =>	335	, 'rubro_id' =>	54	, 'nombre' => 'Pluma de izaje (Provisión - Alquiler - Repuestos - Mantenimiento)']);
        Subrubro::create(['id' =>	336	, 'rubro_id' =>	54	, 'nombre' => 'Pórticos - Balancines - Vigas (fijas o variables)']);
        Subrubro::create(['id' =>	337	, 'rubro_id' =>	54	, 'nombre' => 'Puente Grúa (Provisión - Accesorios - Repuestos - Mantenimiento)']);
        Subrubro::create(['id' =>	338	, 'rubro_id' =>	54	, 'nombre' => 'Sogas para izaje y accesorios']);
        Subrubro::create(['id' =>	339	, 'rubro_id' =>	55	, 'nombre' => 'Escritorios']);
        Subrubro::create(['id' =>	340	, 'rubro_id' =>	55	, 'nombre' => 'Sillas']);
        Subrubro::create(['id' =>	341	, 'rubro_id' =>	55	, 'nombre' => 'Repisas']);
        Subrubro::create(['id' =>	342	, 'rubro_id' =>	55	, 'nombre' => 'Bibliotecas']);
        Subrubro::create(['id' =>	343	, 'rubro_id' =>	55	, 'nombre' => 'Cortinas ']);
        Subrubro::create(['id' =>	344	, 'rubro_id' =>	56	, 'nombre' => 'Monitoreo de concentración de asbestos ']);
        Subrubro::create(['id' =>	345	, 'rubro_id' =>	56	, 'nombre' => 'Monitoreo de efluentes gaseosos y calidad de aire']);
        Subrubro::create(['id' =>	346	, 'rubro_id' =>	56	, 'nombre' => 'Monitoreo del recurso hídrico']);
        Subrubro::create(['id' =>	347	, 'rubro_id' =>	56	, 'nombre' => 'Puesta a tierra']);
        Subrubro::create(['id' =>	348	, 'rubro_id' =>	56	, 'nombre' => 'Calidad de aceite y combustibles ']);
        Subrubro::create(['id' =>	349	, 'rubro_id' =>	56	, 'nombre' => 'Vibraciones, ventilación y estrés térmico. Ruido e Iluminación']);
        Subrubro::create(['id' =>	350	, 'rubro_id' =>	57	, 'nombre' => 'Ensayos y Certificaciones']);
        Subrubro::create(['id' =>	351	, 'rubro_id' =>	57	, 'nombre' => 'Mantenimiento - Reparación']);
        Subrubro::create(['id' =>	352	, 'rubro_id' =>	57	, 'nombre' => 'Montaje']);
        Subrubro::create(['id' =>	353	, 'rubro_id' =>	57	, 'nombre' => 'Repuestos e Insumos']);
        Subrubro::create(['id' =>	354	, 'rubro_id' =>	58	, 'nombre' => 'Baja Tensión']);
        Subrubro::create(['id' =>	355	, 'rubro_id' =>	58	, 'nombre' => 'Media Tensión']);
        Subrubro::create(['id' =>	356	, 'rubro_id' =>	59	, 'nombre' => 'Mantenimiento o Reparaciones']);
        Subrubro::create(['id' =>	357	, 'rubro_id' =>	59	, 'nombre' => 'Montaje']);
        Subrubro::create(['id' =>	358	, 'rubro_id' =>	60	, 'nombre' => 'Motores electicos hasta 380 V - Ensayos']);
        Subrubro::create(['id' =>	359	, 'rubro_id' =>	60	, 'nombre' => 'Motores electicos hasta 380 V - Montaje']);
        Subrubro::create(['id' =>	360	, 'rubro_id' =>	60	, 'nombre' => 'Motores electicos hasta 380 V - Provisión']);
        Subrubro::create(['id' =>	361	, 'rubro_id' =>	60	, 'nombre' => 'Motores electicos hasta 380 V - Reparación']);
        Subrubro::create(['id' =>	362	, 'rubro_id' =>	60	, 'nombre' => 'Motores electicos hasta 380 V - Repuestos']);
        Subrubro::create(['id' =>	363	, 'rubro_id' =>	60	, 'nombre' => 'Motores electicos superior 380 V - Ensayos']);
        Subrubro::create(['id' =>	364	, 'rubro_id' =>	60	, 'nombre' => 'Motores electicos superior 380 V - Montaje']);
        Subrubro::create(['id' =>	365	, 'rubro_id' =>	60	, 'nombre' => 'Motores electicos superior 380 V - Provisión']);
        Subrubro::create(['id' =>	366	, 'rubro_id' =>	60	, 'nombre' => 'Motores electicos superior 380 V - Reparación']);
        Subrubro::create(['id' =>	367	, 'rubro_id' =>	60	, 'nombre' => 'Motores electicos superior 380 V - Repuestos']);
        Subrubro::create(['id' =>	368	, 'rubro_id' =>	61	, 'nombre' => 'Hotelería ']);
        Subrubro::create(['id' =>	369	, 'rubro_id' =>	61	, 'nombre' => 'Casa, Departamento, Cabañas, otros']);
        Subrubro::create(['id' =>	370	, 'rubro_id' =>	61	, 'nombre' => 'Pasajes']);
        Subrubro::create(['id' =>	371	, 'rubro_id' =>	62	, 'nombre' => 'Mantenimiento o Reparación']);
        Subrubro::create(['id' =>	372	, 'rubro_id' =>	62	, 'nombre' => 'Provisión']);
        Subrubro::create(['id' =>	373	, 'rubro_id' =>	62	, 'nombre' => 'Repuestos']);
        Subrubro::create(['id' =>	374	, 'rubro_id' =>	62	, 'nombre' => 'Servicios']);
        Subrubro::create(['id' =>	375	, 'rubro_id' =>	63	, 'nombre' => 'Perforistas ']);
        Subrubro::create(['id' =>	376	, 'rubro_id' =>	63	, 'nombre' => 'Carpinterías metálicas - Construcción, Mantenimiento y Reparaciones']);
        Subrubro::create(['id' =>	377	, 'rubro_id' =>	63	, 'nombre' => 'Cercos perimetrales (alambre - hormigón) - Provisión incluido accesorios, Montaje y Mantenimiento']);
        Subrubro::create(['id' =>	378	, 'rubro_id' =>	63	, 'nombre' => 'Construcción en seco - Construcción y Provisión de componentes']);
        Subrubro::create(['id' =>	379	, 'rubro_id' =>	63	, 'nombre' => 'Desagües cloacales - Construcción, Mantenimiento y Reparaciones']);
        Subrubro::create(['id' =>	380	, 'rubro_id' =>	63	, 'nombre' => 'Desagües pluviales - Construcción, Mantenimiento, Reparaciones y Provision de componentes']);
        Subrubro::create(['id' =>	381	, 'rubro_id' =>	63	, 'nombre' => 'Estructuras metálicas - Construcción, Mantenimiento y Reparaciones']);
        Subrubro::create(['id' =>	382	, 'rubro_id' =>	63	, 'nombre' => 'Impermeabilizaciones']);
        Subrubro::create(['id' =>	383	, 'rubro_id' =>	63	, 'nombre' => 'Instalaciones Eléctricas - Construcción, Mantenimiento y Reparaciones']);
        Subrubro::create(['id' =>	384	, 'rubro_id' =>	63	, 'nombre' => 'Instalaciones Eléctricas - Provisión de elementos e Insumos']);
        Subrubro::create(['id' =>	385	, 'rubro_id' =>	63	, 'nombre' => 'Instalaciones Gas - Construcción, Mantenimiento y Reparaciones']);
        Subrubro::create(['id' =>	386	, 'rubro_id' =>	63	, 'nombre' => 'Instalaciones Gas - Provisión de elementos e Insumos']);
        Subrubro::create(['id' =>	387	, 'rubro_id' =>	63	, 'nombre' => 'Instalaciones Sanitarias - Construcción, Mantenimiento y Reparaciones']);
        Subrubro::create(['id' =>	388	, 'rubro_id' =>	63	, 'nombre' => 'Instalaciones Sanitarias - Provisión de elementos e Insumos']);
        Subrubro::create(['id' =>	389	, 'rubro_id' =>	63	, 'nombre' => 'Mampostería (albañilería) - Reparación y Construcción']);
        Subrubro::create(['id' =>	390	, 'rubro_id' =>	63	, 'nombre' => 'Mantenimiento de Fachadas (Hidrolavado - Pintura)']);
        Subrubro::create(['id' =>	391	, 'rubro_id' =>	63	, 'nombre' => 'Materiales para la Construcción - Provisión']);
        Subrubro::create(['id' =>	392	, 'rubro_id' =>	63	, 'nombre' => 'Pavimentos - Construcción, Mantenimiento y Reparaciones']);
        Subrubro::create(['id' =>	393	, 'rubro_id' =>	63	, 'nombre' => 'Techos - Construcción, Mantenimiento y Reparaciones']);
        Subrubro::create(['id' =>	394	, 'rubro_id' =>	63	, 'nombre' => 'Servicio de desarrollo de planos segun obra']);
        Subrubro::create(['id' =>	395	, 'rubro_id' =>	63	, 'nombre' => 'Servicios, Mantenimiento o Reparación']);
        Subrubro::create(['id' =>	396	, 'rubro_id' =>	64	, 'nombre' => 'Laboral ']);
        Subrubro::create(['id' =>	397	, 'rubro_id' =>	64	, 'nombre' => 'Juridica ']);
        Subrubro::create(['id' =>	398	, 'rubro_id' =>	64	, 'nombre' => 'Impositiva ']);
        Subrubro::create(['id' =>	399	, 'rubro_id' =>	64	, 'nombre' => 'Otros']);
        Subrubro::create(['id' =>	400	, 'rubro_id' =>	65	, 'nombre' => 'Auditoria de Renovación de Certificado de Aptitud Ambiental']);
        Subrubro::create(['id' =>	401	, 'rubro_id' =>	65	, 'nombre' => 'Gestión y asesoramiento de Licencia de Efluentes Gaseosos a la Atmósfera']);
        Subrubro::create(['id' =>	402	, 'rubro_id' =>	65	, 'nombre' => 'Gestión de permisos de explotación y vuelco del recurso hídrico ante ADA y Obras Sanitarias']);
        Subrubro::create(['id' =>	403	, 'rubro_id' =>	65	, 'nombre' => 'Gestion para la obtencion del CAA']);
        Subrubro::create(['id' =>	404	, 'rubro_id' =>	66	, 'nombre' => 'Auditoría Ambiental según Resolución 785/96 //']);
        Subrubro::create(['id' =>	405	, 'rubro_id' =>	66	, 'nombre' => 'Auditoría de Reparación segun 785/96']);
        Subrubro::create(['id' =>	406	, 'rubro_id' =>	66	, 'nombre' => 'Auditoría según Resolución 404/94']);
        Subrubro::create(['id' =>	407	, 'rubro_id' =>	66	, 'nombre' => 'Auditoría Técnica según Resolución 785/96']);
        Subrubro::create(['id' =>	408	, 'rubro_id' =>	67	, 'nombre' => 'Acido Sulfúrico']);
        Subrubro::create(['id' =>	409	, 'rubro_id' =>	67	, 'nombre' => 'Antiincrustante / Dispersante']);
        Subrubro::create(['id' =>	410	, 'rubro_id' =>	67	, 'nombre' => 'Repuestos y Partes']);
        Subrubro::create(['id' =>	411	, 'rubro_id' =>	67	, 'nombre' => 'Servicios']);
        Subrubro::create(['id' =>	412	, 'rubro_id' =>	68	, 'nombre' => 'Soda Cáustica']);
        Subrubro::create(['id' =>	413	, 'rubro_id' =>	68	, 'nombre' => 'Dosificación de ciclos TV']);
        Subrubro::create(['id' =>	414	, 'rubro_id' =>	68	, 'nombre' => 'Otros']);
        Subrubro::create(['id' =>	415	, 'rubro_id' =>	68	, 'nombre' => 'Transporte de productos químicos']);
        Subrubro::create(['id' =>	416	, 'rubro_id' =>	68	, 'nombre' => 'Tratamiento de productos químicos']);
        Subrubro::create(['id' =>	417	, 'rubro_id' =>	69	, 'nombre' => 'Ánodos de sacrificio - Provisión']);
        Subrubro::create(['id' =>	418	, 'rubro_id' =>	69	, 'nombre' => 'Protección anticorrosiva, catódica y conexionado']);
        Subrubro::create(['id' =>	419	, 'rubro_id' =>	69	, 'nombre' => 'Sistemas de protección catódica - Ensayos y Mediciones']);
        Subrubro::create(['id' =>	420	, 'rubro_id' =>	69	, 'nombre' => 'Sistemas de protección catódica - Insumos']);
        Subrubro::create(['id' =>	421	, 'rubro_id' =>	69	, 'nombre' => 'Sistemas de protección catódica - Montaje']);
        Subrubro::create(['id' =>	422	, 'rubro_id' =>	69	, 'nombre' => 'Sistemas de protección catódica - Provisión']);
        Subrubro::create(['id' =>	423	, 'rubro_id' =>	70	, 'nombre' => 'Radiadores, enfriadores, condensadores, calefactores, intercoolers']);
        Subrubro::create(['id' =>	424	, 'rubro_id' =>	71	, 'nombre' => 'Retiro de Chatarra']);
        Subrubro::create(['id' =>	425	, 'rubro_id' =>	71	, 'nombre' => 'Volquetes - Servicio Alquiler']);
        Subrubro::create(['id' =>	426	, 'rubro_id' =>	72	, 'nombre' => 'Retiro y Disposición Final Residuos  Especiales']);
        Subrubro::create(['id' =>	427	, 'rubro_id' =>	73	, 'nombre' => 'Provisión (rodamientos - crapodinas - crucetas - retenes)']);
        Subrubro::create(['id' =>	428	, 'rubro_id' =>	74	, 'nombre' => 'Ropa de trabajo']);
        Subrubro::create(['id' =>	429	, 'rubro_id' =>	75	, 'nombre' => 'Seguros caución']);
        Subrubro::create(['id' =>	430	, 'rubro_id' =>	75	, 'nombre' => 'Seguro automotor']);
        Subrubro::create(['id' =>	431	, 'rubro_id' =>	75	, 'nombre' => 'Seguro medio ambiental']);
        Subrubro::create(['id' =>	432	, 'rubro_id' =>	75	, 'nombre' => 'Seguro responsabilidad civil']);
        Subrubro::create(['id' =>	433	, 'rubro_id' =>	75	, 'nombre' => 'Otros Seguros']);
        Subrubro::create(['id' =>	434	, 'rubro_id' =>	76	, 'nombre' => 'Cartelería de seguridad  (instalaciones, etc.) ']);
        Subrubro::create(['id' =>	435	, 'rubro_id' =>	76	, 'nombre' => 'Señalización en obra y Vías de circulación']);
        Subrubro::create(['id' =>	436	, 'rubro_id' =>	77	, 'nombre' => 'Servicio de Limpieza General']);
        Subrubro::create(['id' =>	437	, 'rubro_id' =>	78	, 'nombre' => 'GAS']);
        Subrubro::create(['id' =>	438	, 'rubro_id' =>	78	, 'nombre' => 'Energía Electrica ']);
        Subrubro::create(['id' =>	439	, 'rubro_id' =>	78	, 'nombre' => 'Agua Potable']);
        Subrubro::create(['id' =>	440	, 'rubro_id' =>	79	, 'nombre' => 'Cajas navideñas']);
        Subrubro::create(['id' =>	441	, 'rubro_id' =>	79	, 'nombre' => 'Otros']);
        Subrubro::create(['id' =>	442	, 'rubro_id' =>	80	, 'nombre' => 'Ensayos y Operatividad del Sistema']);
        Subrubro::create(['id' =>	443	, 'rubro_id' =>	80	, 'nombre' => 'Equipos, Partes e Insumos']);
        Subrubro::create(['id' =>	444	, 'rubro_id' =>	80	, 'nombre' => 'Ingeniería de diseño']);
        Subrubro::create(['id' =>	445	, 'rubro_id' =>	80	, 'nombre' => 'Inspecciones Auditorías Técnicas']);
        Subrubro::create(['id' =>	446	, 'rubro_id' =>	80	, 'nombre' => 'Mantenimiento o Reparaciones']);
        Subrubro::create(['id' =>	447	, 'rubro_id' =>	80	, 'nombre' => 'Montaje']);
        Subrubro::create(['id' =>	448	, 'rubro_id' =>	81	, 'nombre' => 'Servicios Informática']);
        Subrubro::create(['id' =>	449	, 'rubro_id' =>	81	, 'nombre' => 'Informatica Menores']);
        Subrubro::create(['id' =>	450	, 'rubro_id' =>	81	, 'nombre' => 'Enlace de internet - MPLS']);
        Subrubro::create(['id' =>	451	, 'rubro_id' =>	81	, 'nombre' => 'Alquiler de impresoras']);
        Subrubro::create(['id' =>	452	, 'rubro_id' =>	81	, 'nombre' => 'Telefonía básica']);
        Subrubro::create(['id' =>	453	, 'rubro_id' =>	81	, 'nombre' => 'Telefonía móvil']);
        Subrubro::create(['id' =>	454	, 'rubro_id' =>	81	, 'nombre' => 'Servicio de alarma monitoreada']);
        Subrubro::create(['id' =>	455	, 'rubro_id' =>	81	, 'nombre' => 'Servicio de provisión de agua']);
        Subrubro::create(['id' =>	456	, 'rubro_id' =>	81	, 'nombre' => 'Soporte, mantenimiento de sistemas']);
        Subrubro::create(['id' =>	457	, 'rubro_id' =>	81	, 'nombre' => 'Consultoría de sistemas']);
        Subrubro::create(['id' =>	458	, 'rubro_id' =>	81	, 'nombre' => 'Licencias software']);
        Subrubro::create(['id' =>	459	, 'rubro_id' =>	81	, 'nombre' => 'Provisión de sottware']);
        Subrubro::create(['id' =>	460	, 'rubro_id' =>	81	, 'nombre' => 'Central telefonica Telefonia IP - Telefonos IP']);
        Subrubro::create(['id' =>	461	, 'rubro_id' =>	81	, 'nombre' => 'Swtichs - routers - WIFI']);
        Subrubro::create(['id' =>	462	, 'rubro_id' =>	81	, 'nombre' => 'PC / Laptops ']);
        Subrubro::create(['id' =>	463	, 'rubro_id' =>	81	, 'nombre' => 'Monitores / Insumos informáticos ']);
        Subrubro::create(['id' =>	464	, 'rubro_id' =>	81	, 'nombre' => 'Adquisicion de equipamientos de networking (hardware)']);
        Subrubro::create(['id' =>	465	, 'rubro_id' =>	82	, 'nombre' => 'Calibración, Ensayos y Certificaciones ']);
        Subrubro::create(['id' =>	466	, 'rubro_id' =>	82	, 'nombre' => 'Desgasificación']);
        Subrubro::create(['id' =>	467	, 'rubro_id' =>	82	, 'nombre' => 'Impermeabilización y Pintura ']);
        Subrubro::create(['id' =>	468	, 'rubro_id' =>	82	, 'nombre' => 'Limpieza']);
        Subrubro::create(['id' =>	469	, 'rubro_id' =>	82	, 'nombre' => 'Reparación o Mantenimiento ']);
        Subrubro::create(['id' =>	470	, 'rubro_id' =>	83	, 'nombre' => 'Fabricación']);
        Subrubro::create(['id' =>	471	, 'rubro_id' =>	83	, 'nombre' => 'Provisión']);
        Subrubro::create(['id' =>	472	, 'rubro_id' =>	83	, 'nombre' => 'Reparación']);
        Subrubro::create(['id' =>	473	, 'rubro_id' =>	84	, 'nombre' => 'Herramientas']);
        Subrubro::create(['id' =>	474	, 'rubro_id' =>	84	, 'nombre' => 'Insumos']);
        Subrubro::create(['id' =>	475	, 'rubro_id' =>	84	, 'nombre' => 'Materia Prima']);
        Subrubro::create(['id' =>	476	, 'rubro_id' =>	84	, 'nombre' => 'Provisión de equipos']);
        Subrubro::create(['id' =>	477	, 'rubro_id' =>	84	, 'nombre' => 'Reparación de herramienta o equipo']);
        Subrubro::create(['id' =>	478	, 'rubro_id' =>	85	, 'nombre' => 'Transformador de Comando BT - Mantenimiento']);
        Subrubro::create(['id' =>	479	, 'rubro_id' =>	85	, 'nombre' => 'Transformador de Comando BT - Provisión']);
        Subrubro::create(['id' =>	480	, 'rubro_id' =>	85	, 'nombre' => 'Transformador de Medición AT (Tensión y Corriente) - Accesorios y Repuestos']);
        Subrubro::create(['id' =>	481	, 'rubro_id' =>	85	, 'nombre' => 'Transformador de Medición AT (Tensión y Corriente) - Mantenimiento']);
        Subrubro::create(['id' =>	482	, 'rubro_id' =>	85	, 'nombre' => 'Transformador de Medición AT (Tensión y Corriente) - Montaje']);
        Subrubro::create(['id' =>	483	, 'rubro_id' =>	85	, 'nombre' => 'Transformador de Medición AT (Tensión y Corriente) - Provisión']);
        Subrubro::create(['id' =>	484	, 'rubro_id' =>	85	, 'nombre' => 'Transformador de Medición AT/MT (Tensión y Corriente) - Ensayos Eléctricos']);
        Subrubro::create(['id' =>	485	, 'rubro_id' =>	85	, 'nombre' => 'Transformador de Medición MT (Tensión y Corriente) - Accesorios y Repuestos']);
        Subrubro::create(['id' =>	486	, 'rubro_id' =>	85	, 'nombre' => 'Transformador de Medición MT (Tensión y Corriente) - Mantenimiento']);
        Subrubro::create(['id' =>	487	, 'rubro_id' =>	85	, 'nombre' => 'Transformador de Medición MT (Tensión y Corriente) - Montaje']);
        Subrubro::create(['id' =>	488	, 'rubro_id' =>	85	, 'nombre' => 'Transformador de Medición MT (Tensión y Corriente) - Provisión']);
        Subrubro::create(['id' =>	489	, 'rubro_id' =>	85	, 'nombre' => 'Transformador de Potencia AT/MT - Accesorios y Repuestos']);
        Subrubro::create(['id' =>	490	, 'rubro_id' =>	85	, 'nombre' => 'Transformador de Potencia AT/MT - Mantenimiento']);
        Subrubro::create(['id' =>	491	, 'rubro_id' =>	85	, 'nombre' => 'Transformador de Potencia AT/MT - Montaje']);
        Subrubro::create(['id' =>	492	, 'rubro_id' =>	85	, 'nombre' => 'Transformador de Potencia AT/MT - Provisión']);
        Subrubro::create(['id' =>	493	, 'rubro_id' =>	85	, 'nombre' => 'Transformador de Potencia AT/MT/BT - Ensayos Eléctricos']);
        Subrubro::create(['id' =>	494	, 'rubro_id' =>	85	, 'nombre' => 'Transformador de Potencia AT/MT/BT - Ensayos Químicos']);
        Subrubro::create(['id' =>	495	, 'rubro_id' =>	85	, 'nombre' => 'Transformador de Potencia MT/BT - Accesorios y Repuestos']);
        Subrubro::create(['id' =>	496	, 'rubro_id' =>	85	, 'nombre' => 'Transformador de Potencia MT/BT - Mantenimiento']);
        Subrubro::create(['id' =>	497	, 'rubro_id' =>	85	, 'nombre' => 'Transformador de Potencia MT/BT - Montaje']);
        Subrubro::create(['id' =>	498	, 'rubro_id' =>	85	, 'nombre' => 'Transformador de Potencia MT/BT - Provisión']);
        Subrubro::create(['id' =>	499	, 'rubro_id' =>	86	, 'nombre' => 'Automóvil']);
        Subrubro::create(['id' =>	500	, 'rubro_id' =>	86	, 'nombre' => 'Camión - Furgón']);
        Subrubro::create(['id' =>	501	, 'rubro_id' =>	86	, 'nombre' => 'Camión pesado - Tráiler']);
        Subrubro::create(['id' =>	502	, 'rubro_id' =>	86	, 'nombre' => 'Camioneta - Furgoneta - Pick up']);
        Subrubro::create(['id' =>	503	, 'rubro_id' =>	87	, 'nombre' => 'Arenado (in situ - en fábrica)']);
        Subrubro::create(['id' =>	504	, 'rubro_id' =>	87	, 'nombre' => 'Hidrolavados']);
        Subrubro::create(['id' =>	505	, 'rubro_id' =>	87	, 'nombre' => 'Insumos de Granallado - Provisión']);
        Subrubro::create(['id' =>	506	, 'rubro_id' =>	87	, 'nombre' => 'Insumos de pintura - Provisión']);
        Subrubro::create(['id' =>	507	, 'rubro_id' =>	87	, 'nombre' => 'Limpieza por Hielo Seco - Servicio']);
        Subrubro::create(['id' =>	508	, 'rubro_id' =>	87	, 'nombre' => 'Metalizados']);
        Subrubro::create(['id' =>	509	, 'rubro_id' =>	87	, 'nombre' => 'Zincados']);
        Subrubro::create(['id' =>	510	, 'rubro_id' =>	88	, 'nombre' => 'Cojinetes']);
        Subrubro::create(['id' =>	511	, 'rubro_id' =>	88	, 'nombre' => 'Elementos de máquina']);
        Subrubro::create(['id' =>	512	, 'rubro_id' =>	88	, 'nombre' => 'In situ']);
        Subrubro::create(['id' =>	513	, 'rubro_id' =>	88	, 'nombre' => 'Servicio']);
        Subrubro::create(['id' =>	514	, 'rubro_id' =>	89	, 'nombre' => 'Aceros especiales para cojinetes']);
        Subrubro::create(['id' =>	515	, 'rubro_id' =>	89	, 'nombre' => 'Aceros especiales para ejes']);
        Subrubro::create(['id' =>	516	, 'rubro_id' =>	89	, 'nombre' => 'Aceros especiales para engranajes']);
        Subrubro::create(['id' =>	517	, 'rubro_id' =>	89	, 'nombre' => 'Caños Acero Inoxidable y accesorios']);
        Subrubro::create(['id' =>	518	, 'rubro_id' =>	89	, 'nombre' => 'Caños Galvanizados y accesorios']);
        Subrubro::create(['id' =>	519	, 'rubro_id' =>	89	, 'nombre' => 'Caños PVC y accesorios']);
        Subrubro::create(['id' =>	520	, 'rubro_id' =>	89	, 'nombre' => 'Chapas y Planchuelas Pesadas']);
        Subrubro::create(['id' =>	521	, 'rubro_id' =>	89	, 'nombre' => 'Metales No Ferrosos']);
        Subrubro::create(['id' =>	522	, 'rubro_id' =>	89	, 'nombre' => 'Tochos']);
        Subrubro::create(['id' =>	523	, 'rubro_id' =>	89	, 'nombre' => 'Tubos con costura']);
        Subrubro::create(['id' =>	524	, 'rubro_id' =>	89	, 'nombre' => 'Tubos especiales']);
        Subrubro::create(['id' =>	525	, 'rubro_id' =>	89	, 'nombre' => 'Tubos sin costura']);
        Subrubro::create(['id' =>	526	, 'rubro_id' =>	90	, 'nombre' => 'Filtros de aire']);
        Subrubro::create(['id' =>	527	, 'rubro_id' =>	90	, 'nombre' => 'Inspección - Diagnóstico - Ensayos']);
        Subrubro::create(['id' =>	528	, 'rubro_id' =>	90	, 'nombre' => 'Mantenimiento']);
        Subrubro::create(['id' =>	529	, 'rubro_id' =>	90	, 'nombre' => 'Reparaciones']);
        Subrubro::create(['id' =>	530	, 'rubro_id' =>	90	, 'nombre' => 'Repuestos - Partes - Consumibles (Menores)']);
        Subrubro::create(['id' =>	531	, 'rubro_id' =>	90	, 'nombre' => 'Repuestos - Partes (Capitales)']);
        Subrubro::create(['id' =>	532	, 'rubro_id' =>	91	, 'nombre' => 'Inspección - Diagnóstico - Ensayos']);
        Subrubro::create(['id' =>	533	, 'rubro_id' =>	91	, 'nombre' => 'Mantenimiento']);
        Subrubro::create(['id' =>	534	, 'rubro_id' =>	91	, 'nombre' => 'Reparaciones']);
        Subrubro::create(['id' =>	535	, 'rubro_id' =>	91	, 'nombre' => 'Repuestos - Partes - Consumibles (Menores)']);
        Subrubro::create(['id' =>	536	, 'rubro_id' =>	91	, 'nombre' => 'Repuestos - Partes (Capitales)']);
        Subrubro::create(['id' =>	537	, 'rubro_id' =>	92	, 'nombre' => 'Mantenimiento/Reparación']);
        Subrubro::create(['id' =>	538	, 'rubro_id' =>	92	, 'nombre' => 'Montaje']);
        Subrubro::create(['id' =>	539	, 'rubro_id' =>	92	, 'nombre' => 'Provisión']);
        Subrubro::create(['id' =>	540	, 'rubro_id' =>	92	, 'nombre' => 'Repuestos (Estabilizador - Inversor - Baterías - Cargador Baterías - Otros)']);
        Subrubro::create(['id' =>	541	, 'rubro_id' =>	93	, 'nombre' => 'Electroválvulas - Provisión']);
        Subrubro::create(['id' =>	542	, 'rubro_id' =>	93	, 'nombre' => 'Otras Válvulas - Provisión']);
        Subrubro::create(['id' =>	543	, 'rubro_id' =>	93	, 'nombre' => 'Válvula de bloqueo o cierre (líquido; gas; vapor; líquido con sólidos; gas con sólidos; líquido con gas; con o sin erosión; con o sin corrosión) - Provisión']);
        Subrubro::create(['id' =>	544	, 'rubro_id' =>	93	, 'nombre' => 'Válvula de control (líquido; gas; vapor; líquido con sólidos; gas con sólidos; líquido con gas; con o sin erosión; con o sin corrosión) - Provisión']);
        Subrubro::create(['id' =>	545	, 'rubro_id' =>	93	, 'nombre' => 'Válvula de retención (líquido; gas; vapor; líquido con sólidos; gas con sólidos; líquido con gas; con o sin erosión; con o sin corrosión) - Provisión']);
        Subrubro::create(['id' =>	546	, 'rubro_id' =>	93	, 'nombre' => 'Válvulas - Calibración']);
        Subrubro::create(['id' =>	547	, 'rubro_id' =>	93	, 'nombre' => 'Válvulas - Reparación']);
        Subrubro::create(['id' =>	548	, 'rubro_id' =>	93	, 'nombre' => 'Válvulas - Repuestos']);

    }
}
